name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'foreverBackend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy Backend via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "✅ Connected to EC2!"
            echo "🚀 Updating backend..."
            cd ~/Desktop/foreverBackend
            git pull
            npm install
            pm2 restart all
            echo "✅ Backend deploy done!"
